services:
  - type: web
    name: flodon-internal-crm
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - fromGroup: "flodon-secrets"
